# Generated by Django 3.0.6 on 2020-09-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200908_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_country',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_profile',
        ),
    ]
