# Generated by Django 3.0.6 on 2020-09-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200908_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile'),
        ),
    ]
