# Generated by Django 3.0.6 on 2020-09-10 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200910_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.UserProfile'),
        ),
    ]
